###########################################################################
# Docker Compose File
###########################################################################
#
# Your Docker Compose file spins up your application's environment.
# It defines all of the services, network links and volumes to
# be used by your application. Modify this file as required.
#
version: '2'
services:
  {{#services}}
  {{name}}:
    {{#if build}} 
    build: {{build}}
    {{/if}}
    {{#if image}} 
    image: {{image}}
    {{/if}}
    {{#volumes}} 
    volumes:
      {{#each this}}
      - {{@key}}:{{{this}}}
      {{/each}}
    {{/volumes}}
    ports:
      {{#ports}}
      - "{{this}}"
      {{/ports}}
    {{#environment}}
    environment: 
    {{#each this}}
      {{@key}}: {{{this}}}
    {{/each}}
    {{/environment}}
    {{#if command}} 
    command: {{{command}}}
    {{/if}}
    
  {{/services}}